apiVersion: v1
kind: Service
metadata:
  name: quarkus-kafka-toots-faker
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: quarkus-kafka-toots-faker
  sessionAffinity: None
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: quarkus-kafka-toots-faker
  labels:
    app.kubernetes.io/part-of: streaming-apps
    app.openshift.io/runtime: quarkus
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"kafka"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-kafka-toots-faker
  template:
    metadata:
      labels:
        app: quarkus-kafka-toots-faker
    spec:
      containers:
      - name: quarkus-kafka-toots-faker
        image: quay.io/hgrahsl/toots-faker:1.0
        env:
          - name: TOOTSFAKER_TWEET_INTERVAL_MS
            value: "500"
          - name: TOOTSFAKER_MAX_TWEET_LENGTH
            value: "320"
          - name: TOOTSFAKER_TOOTS_TOPIC_PARTITIONS
            value: "4"
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
        imagePullPolicy: Always
      restartPolicy: Always
