apiVersion: v1
kind: Service
metadata:
  name: quarkus-kafka-toots-harvester
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: quarkus-kafka-toots-harvester
  sessionAffinity: None
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: quarkus-kafka-toots-harvester
  labels:
    app.kubernetes.io/part-of: streaming-apps
    app.openshift.io/runtime: quarkus
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"kafka"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-kafka-toots-harvester
  template:
    metadata:
      labels:
        app: quarkus-kafka-toots-harvester
    spec:
      containers:
      - name: quarkus-kafka-toots-harvester
        image: quay.io/hgrahsl/toots-harvester:1.0
        env:
          - name: MASTODON_API_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: mastodon-api
                key: access-token
          - name: TOOTSHARVESTER_TOOTS_TOPIC_PARTITIONS
            value: "4"
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
        imagePullPolicy: Always
      restartPolicy: Always
